version: '3'
services:

  api:
    image: docker-registry-default.apps.os-gamma.ole.redhat.com/crowdpong/crowdpong-api:latest
    environment:
      CONTAINER_DEBUG: 1
    ports:
      - "8091:8080"
    volumes:
      - ./api:/opt/app-root/src

  board:
    image: docker-registry-default.apps.os-gamma.ole.redhat.com/crowdpong/crowdpong-board-client:latest
    environment:
      DEV_MODE: 'true'
    ports:
      - "8092:8080"
    volumes:
      - ./board-client:/opt/app-root/src

  controller:
    image: docker-registry-default.apps.os-gamma.ole.redhat.com/crowdpong/crowdpong-controller-client:latest
    environment:
      DEV_MODE: 'true'
    ports:
      - "8000:8080"
    volumes:
      - ./controller-client:/opt/app-root/src

  redis:
    image: redis
    ports: 
      - "6379:6379"
    volumes:
      - redis:/var/lib/redis/data

volumes:
  redis:

